name: Create Auto Pull Request
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  update-dep:
    runs-on: ubuntu-latest

    # Only intended for forks.
    if: github.repository == 'jeromepatel/optuna'

    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get -y install openmpi-bin libopenmpi-dev libopenblas-dev
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install --use-deprecated=legacy-resolver --progress-bar off pip-check
          pip install --use-deprecated=legacy-resolver --progress-bar off .[tests]
          pip install --use-deprecated=legacy-resolver --progress-bar off .[integration] -f https://download.pytorch.org/whl/torch_stable.html

      - name: Run Pip-check
        run: |
          pip-check - H > Pip-updates
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: update authors
          title: Show Updated Pip Dependencies
          body: This is an autogenerated pull request resulted from a dependency check test
          base: master
          branch: pip-check-difference